Feature/add user
RafaelPires2/onboard-instituto-mobile pull request #5
Opened 2023-05-05 19:01 UTC by RafaelPires2

![image](https://user-images.githubusercontent.com/86695046/236546483-c9121c37-4473-4a5f-b472-a96298e03e0c.png)

2023-05-05 19:36 UTC, dan-ueno requested changes
primeiro ponto aqui: acho que vc poderia ter separado esse pr em mais prs, pois tem várias coisas de diferentes camadas e objetivos (pode ser que o apontamento do seu pr esteja errado, se vc tiver varios, acabei nao vendo)

algumas dicas de padronização acho que ainda não foram dadas então considera para aprendizado e não necessariamente precisa alterar. Outras que podem quebrar o código eu sugiro que vc repense um pouco e veja pq seria legal de mudar (como o children no text do button). Qualquer dúvida pode me chamar no slack e a gente bate um papo =]

2023-05-05 19:36 UTC, dan-ueno commented on package.json
> +    "@types/react": "~18.0.27",
no package json é melhor deixar as versões fixadas

2023-05-05 19:36 UTC, dan-ueno commented on src/@types/navigation.d.ts
> +      Login: undefined;
achei estranho esses undefineds, não dá para tipar um pouco mais especifico?

2023-05-05 19:36 UTC, dan-ueno commented on src/components/button/index.tsx
> +      <TextButton>{children}</TextButton>
vendo aqui, acho que seria melhor vc em vez de receber um children no button receber uma string, pois senao vc permite que tenha view dentro de text e etc e isso pode gerar problemas no futuro, e no caso o botão tem que ter alguma string entao nao fica opcional haha

2023-05-05 19:36 UTC, dan-ueno commented on src/components/button/styles.ts
> +  height: 47px;
não sei se ja te comentaram com valores hardcodeds, mas essa altura fica muito específica ai dentro dessa linha, entao por mais que ela apareça apenas ai é melhor vc separar em uma const que dê o significado para esse valor

2023-05-05 19:36 UTC, dan-ueno commented on src/components/float-button/index.tsx
> +        <TextFloatButton>{children}</TextFloatButton>
mesma ideia do comentário anterior

2023-05-05 19:36 UTC, dan-ueno commented on src/components/float-button/styles.ts
> +  width: 50px;
mesma ideia do comentário anterior dos valores chumbados

2023-05-05 19:36 UTC, dan-ueno commented on src/components/input/styles.ts
> +  gap: 8px;
mesma coisa, mas aqui quero so aproveitar para falar dos nomes dos arquivos...index vc puxa direto da página, mas a gente costuma nomear um pouco melhor e exportar o componente pq ai no command / control + P fica fácil de navegar entre os arquivos:

index --> exporta arquivo de component (raramente o de style)
arquivo de componente --> `<component>.component.tsx`
arquivo de estilo --> `<component>.component.style.tsx`

2023-05-05 19:36 UTC, dan-ueno commented on src/components/input/styles.ts
> +  width: ${wp('80%')}px;
acho que reduzir o nome aqui mais atrapalha do que ajuda kkkk

2023-05-05 19:36 UTC, dan-ueno commented on src/components/input/styles.ts
> +export const WrapperInputOption = styled.View`
aliás, as consts de estilo levam a categoria no nome, entao ficaria `WrapperInputOptionStyled`

2023-05-05 19:36 UTC, dan-ueno commented on src/components/user-item/index.tsx
> +      <Text>ID: {id}</Text>
geralmente a gente separa um arquivo de string também, para evitar de deixar coisas chumbadas que a gente precise mudar depois

2023-05-05 19:36 UTC, dan-ueno commented on src/components/users-list/index.tsx
> +  const { loading, error, data, fetchMore } = useQuery(LIST_USERS_QUERY, {
a chamada para o graphql dá para separar em um custom hook

2023-05-05 19:36 UTC, dan-ueno commented on src/contexts/auth.tsx
> +export const AuthProvider: React.FC<Props> = ({ children }) => {
os arquivos de contexto e provider podem ficar em arquivos separados tbm

2023-05-05 19:36 UTC, dan-ueno commented on src/pages/add-user/index.tsx
> +const formSchemaAddUser = z.object({
isso aqui é um utilitário (inclusive se vc separar cada método vc pode reaproveitar depois)

Nao faz parte da responsabilidade da página ter essa regra

2023-05-05 19:36 UTC, dan-ueno commented on src/pages/dashboard/index.tsx
> +    <FloatButton onPress={() => navigation.navigate('ScreenAddUser')}>+</FloatButton>
o ponto de ter em string assim é que vc ta permitindo erro, se vc tiver um typo na sua rota vai dar problema..entao ali quando vc fez a rota, vc pode criar um enum que identifica cada rota que vc cadastrou e ai garante que vai estar sempre correto

2023-05-08 17:21 UTC, racsandoval reviewed
realmente, esse PR ficou bem grande

2023-05-08 17:21 UTC, racsandoval commented on src/components/button/styles.ts
> +  height: 47px;
geralmente deixamos essas consts em caixa alta
`const BUTTON_HEIGHT = 47px;`

2023-05-08 17:21 UTC, racsandoval commented on src/components/input/styles.ts
> +  gap: 8px;
só para conhecimento, nos projetos nós temos um arquivo de constantes para manter a consistência em alguns números que são reutilizados no projeto todo, aqui um exemplo:
```
const Spacing: {
  xs: '4px',
  sm: '8px',
  md: '16px',
  lg: '32px',
}
```

2023-05-10 14:55 UTC, merged